### PR TITLE
las2json, json2las, delimiter, null

### PR DESCRIPTION
**Pull request by jackymyh**
Attached my take on las2json and json2las functions that could also accept LAS 3.0 file for different delimiters.

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Thanks for the contribution @jackymyh ! 

I'll try to find some time later this week to give this a go.

**Comment by dcslagel** [comment]
Hi @JustinGOSSES, @jackymyh, 

Enabling  LAS 3.0 seems like a positive thing to do.  

I did an initial read through of this Pull Request's code.  Here are a few questions that should be considered.

1.  Overall design:  How should these new functions coordinate with wellio.js's main las2json function.  Should they be merged into las2json, or called from las2json (perhaps when  a LAS file is identified as LAS 3.0)?

2. It looks like the internal Json in these functions uses a different naming scheme from wellio.js.  Which naming scheme should be used?

Thanks!,
DC

**Comment by JustinGOSSES** [comment]
Just wanted to let everyone know I'm swamped with covid-19 response activities at work and won't have free time to get to this by now like I thought.

**Comment by dcslagel** [comment]
@JustinGOSSES, 

Thank you for the update. I hope you and your family, friends and colleagues are safe during the current situation.

DC

**Comment by JustinGOSSES** [comment]
Thanks DC. Same to you!

**Comment by JustinGOSSES** [comment]
Agree with @dcslagel that the naming convention needs work to avoid confusion with similar functions for las2.0. @jackymyh do you think you could re-work it to follow the established naming conventions more closely but have a part in there that explicitly says v3 or 3? 

Version 2.0 LAS are more common than 2.0, so it would be nice to keep that as the default and have version 3.0 treated as a flagged condition for different behavior.

**Comment by JustinGOSSES** [comment]
reopening this stale pull request as this would be nice to integrate into the product

**Comment by dcslagel** [comment]
Is there a way to flag this pull-request so GitHub-actions won't keep closing it?

**Pull request closed without merging**
